<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Device Tree editor</title>
		<link rel="stylesheet" href="/jquery-ui/jquery-ui.css">
		<link rel="stylesheet" href="/bootstrap/css/bootstrap.min.css">
		<link rel="stylesheet" href="/bootstrap/css/bootstrap-theme.min.css">
		<script src="/jquery.loadmask.js"></script>
		<script src="/bootstrap/js/bootstrap.min.js"></script>
		<link rel="stylesheet" href="/boards.css">
	</head>
	<body>
		<div class="container">
			<br><br><br><br>
			<div class="jumbotron">
				<h1>Board unsupported!</h1>
				<p>Your board is unsupported by this version of DTweb @_@</p>
			</div>
		</div>
	</body>
</html>