<br>

<div class="row-fluid">
	
	<div class="col-sm-4">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<h3 class="panel-title">Available features</h3>
			</div>
			<div class="panel-body">
				<ul class="list-group" id="features">
				</ul>
			</div>
		</div>
		
		<div class="panel panel-primary">
			<div class="panel-heading">
				<h3 class="panel-title">Configuration</h3>
			</div>
			<div class="panel-body">
				<button class="btn btn-primary" id="save-btn">Apply</button>
				<button class="btn btn-warning" id="reset-btn">Reset</button>
			</div>
		</div>
	</div>
	
	<div class="col-sm-8">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<h3 class="panel-title" id="board-name">Board</h3>
			</div>
			<div class="panel-body board-ct">
				<div id="board"></div>
			</div>
		</div>
	</div>
	
</div>

<div class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Device Tree editor</h4>
      </div>
      <div class="modal-body">
        <p id="modal-msg"></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
