<br>

<div class="row-fluid">
	
	<div class="col-md-4">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<h3 class="panel-title">Available features</h3>
			</div>
			<div class="panel-body">
				<ul class="list-group" id="features">
				</ul>
			</div>
		</div>
		
		<div class="panel panel-primary">
			<div class="panel-heading">
				<h3 class="panel-title">Configuration</h3>
			</div>
			<div class="panel-body">
				<button class="btn btn-primary" id="save-btn">Apply</button>
				<button class="btn btn-warning" id="reset-btn">Reset</button>
			</div>
		</div>
	</div>
	
	<div class="col-md-8">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<h3 class="panel-title" id="board-name">Board</h3>
			</div>
			<div class="panel-body board-ct">
				<div id="board"></div>
			</div>
		</div>
	</div>
	
</div>
