#!/bin/sh
set -e

case "$1" in
    configure)
        cd /opt/dtweb
        echo "Removing dtbkernel..."
        rm -rf dtbkernel || true

        if ls /lib/modules/3.14* 1> /dev/null 2>&1; then
            KERNEL_MAJOR=3
        else
            KERNEL_MAJOR=4
        fi

        if [ "$KERNEL_MAJOR" = "4" ]; then
            echo "Linux 4 detected!"
            tar xfj dtbkernel4.tar.bz2
        else
            echo "Linux 3 detected!"
            tar xfj dtbkernel.tar.bz2
        fi

        chown -R root:root dtbkernel
        cd dtbkernel
        chmod -R 666 arch/arm/boot/dts
        mkdir -p arch/arm/boot/dts/include || true
        (cd arch/arm/boot/dts/include; ln -s ../../../../../include/dt-bindings || true)

        echo "Making a test DTB..."
        make -j4 imx6q-udoo-hdmi.dtb
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
