#!/bin/sh
set -e

case "$1" in
    configure)
        cd /opt/dtweb
        echo "Removing dtbkernel..."
        rm -rf dtbkernel || true

        KERNEL_MAJOR=`uname -r | head -c1`
        echo $KERNEL_MAJOR

        if [ "$KERNEL_MAJOR" == "4" ]; then
            echo "Linux 4 detected!"
            echo "Unpacking dtbkernel..."
            tar xfj dtbkernel4.tar.bz2
            chown -R root:root dtbkernel
            cd dtbkernel
            chmod -R 666 arch/arm/boot/dts
        else
            echo "Linux 3 detected!"
            echo "Unpacking dtbkernel..."
            tar xfj dtbkernel.tar.bz2
            chown -R root:root dtbkernel
            cd dtbkernel
            chmod -R 666 arch/arm/boot/dts
            (cd arch/arm/boot/dts/include; ln -s ../../../../../include/dt-bindings || true)
        fi

        echo "Making a test DTB..."
        make -j4 imx6q-udoo-hdmi.dtb
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
