#!/bin/sh
set -e

case "$1" in
    remove|upgrade|deconfigure)
        cd /usr/local/bin/dtweb
        rm -rf dtbkernel
    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
